CREATE DATABASE IF NOT EXISTS wordpress_db;
CREATE DATABASE IF NOT EXISTS moodle_db;

GRANT ALL PRIVILEGES ON wordpress_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON moodle_db.* TO 'user'@'%';

FLUSH PRIVILEGES;
